package rcli

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/mevijays/goca/internal/gocaclient"
	"github.com/mevijays/goca/internal/pki"
	"github.com/mevijays/goca/internal/termio"
)

func newCertCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "cert",
		Short:   "Issue, find, renew and revoke certificates",
		Aliases: []string{"certs", "certificate"},
	}
	cmd.AddCommand(
		newCertIssueCmd(),
		newCertSignCmd(),
		newCertListCmd(),
		newCertShowCmd(),
		newCertExportCmd(),
		newCertRenewCmd(),
		newCertHistoryCmd(),
		newCertRevokeCmd(),
		newCertHoldCmd(),
		newCertReleaseCmd(),
		newCertDeleteCmd(),
	)
	return cmd
}

func newCertListCmd() *cobra.Command {
	var (
		query, caRef, status, profile, requestedBy string
		expiringIn, limit, offset                  int
		sortBy                                     string
		desc                                       bool
	)
	cmd := &cobra.Command{
		Use:     "list",
		Aliases: []string{"ls"},
		Short:   "Search issued certificates",
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			res, err := c.ListCerts(ctx, gocaclient.CertFilter{
				Query: query, CARef: caRef, Status: status, Profile: profile,
				RequestedBy: requestedBy, ExpiringIn: expiringIn,
				Limit: limit, Offset: offset, SortBy: sortBy, SortDesc: desc,
			})
			if err != nil {
				return err
			}
			if flagJSON {
				return termio.PrintRaw(res.Raw)
			}
			certs := res.Value.Certificates
			if len(certs) == 0 {
				fmt.Println("No certificates matched.")
				return nil
			}
			t := termio.NewTable("id", "common name", "authority", "profile", "status", "expires", "days", "key", "requested by")
			for _, c := range certs {
				key := "-"
				if c.HasKey {
					key = "stored"
				}
				t.Row(c.ID, c.CommonName, c.CAName, c.Profile, c.EffectiveStatus(),
					c.NotAfter.Format("2006-01-02"), c.DaysLeft(), key, c.RequestedBy)
			}
			t.Flush()
			fmt.Printf("\n%d of %d shown\n", len(certs), res.Value.Total)
			return nil
		},
	}
	fl := cmd.Flags()
	fl.StringVarP(&query, "query", "q", "", "match CN, subject, serial, SANs or requester")
	fl.StringVar(&caRef, "ca", "", "only this authority")
	fl.StringVar(&status, "status", "", "active|revoked|expired")
	fl.StringVar(&profile, "profile", "", "server|client|server-client|code-signing|email")
	fl.StringVar(&requestedBy, "requested-by", "", "only this requester")
	fl.IntVar(&expiringIn, "expiring-in", 0, "only those expiring within N days")
	fl.IntVar(&limit, "limit", 0, "maximum rows")
	fl.IntVar(&offset, "offset", 0, "skip this many rows")
	fl.StringVar(&sortBy, "sort", "", "created_at|not_after|common_name")
	fl.BoolVar(&desc, "desc", false, "sort descending")
	return cmd
}

func newCertIssueCmd() *cobra.Command {
	var (
		caRef, cn, org, ou          string
		country, province, locality string
		sans                        []string
		keyType, profile            string
		days                        int
		outDir                      string
		noStoreKey                  bool
		note                        string
	)
	cmd := &cobra.Command{
		Use:   "issue",
		Short: "Issue a certificate, generating the key on the server",
		Long: strings.TrimSpace(`
The key is generated by the server and returned once. If you would rather the
key never leave this machine, generate it locally with ` + "`gocactl csr new`" + `
and sign it with ` + "`gocactl cert sign`" + `.`),
		Example: strings.TrimSpace(`
  gocactl cert issue --common-name app.internal.lan --san app.internal.lan --days 397 --out ./app`),
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			storeKey := !noStoreKey
			res, err := c.IssueCert(ctx, gocaclient.IssueInput{
				CARef: caRef,
				Mode:  "generate",
				Subject: pki.Subject{
					CommonName: cn, Organization: org, OrganizationalUnit: ou,
					Country: country, Province: province, Locality: locality,
				},
				SANs:     sans,
				KeyType:  keyType,
				Profile:  profile,
				Days:     days,
				StoreKey: &storeKey,
				Note:     note,
			})
			if err != nil {
				return err
			}
			if flagJSON {
				return termio.PrintRaw(res.Raw)
			}
			return reportIssue(res.Value, outDir, noStoreKey)
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&caRef, "ca", "", "issuing authority (default: the server's default)")
	fl.StringVar(&cn, "common-name", "", "subject common name (CN)")
	fl.StringVar(&org, "organization", "", "subject organization (O)")
	fl.StringVar(&ou, "organizational-unit", "", "subject organizational unit (OU)")
	fl.StringVar(&country, "country", "", "subject country code (C)")
	fl.StringVar(&province, "province", "", "subject state/province (ST)")
	fl.StringVar(&locality, "locality", "", "subject locality (L)")
	fl.StringSliceVar(&sans, "san", nil, "subject alternative name (repeatable)")
	fl.StringVar(&keyType, "key-type", "", "key algorithm")
	fl.StringVar(&profile, "profile", "", "server|client|server-client|code-signing|email")
	fl.IntVar(&days, "days", 0, "validity in days")
	fl.StringVar(&outDir, "out", "", "write cert, key and chains into this directory")
	fl.BoolVar(&noStoreKey, "no-store-key", false, "do not retain the key server-side (download-once)")
	fl.StringVar(&note, "note", "", "free-text note stored with the certificate")
	return cmd
}

func newCertSignCmd() *cobra.Command {
	var (
		caRef, csrFile, keyFile string
		profile                 string
		days                    int
		certOut, outDir         string
		note                    string
	)
	cmd := &cobra.Command{
		Use:   "sign",
		Short: "Sign a CSR you already have",
		Long: strings.TrimSpace(`
Your private key stays where it is - only the request is sent. Pair this with
` + "`gocactl csr new`" + `, which generates the key locally, for a workflow where
the key never touches the network.`),
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			if csrFile == "" {
				return fmt.Errorf("--csr is required")
			}
			csrPEM, err := os.ReadFile(csrFile)
			if err != nil {
				return err
			}
			var keyPEM []byte
			if keyFile != "" {
				// Only when the user explicitly asks goca to retain the key so
				// the bundle stays re-downloadable.
				if keyPEM, err = os.ReadFile(keyFile); err != nil {
					return err
				}
			}
			c, err := client()
			if err != nil {
				return err
			}
			res, err := c.IssueCert(ctx, gocaclient.IssueInput{
				CARef:   caRef,
				Mode:    "csr",
				CSRPEM:  string(csrPEM),
				KeyPEM:  string(keyPEM),
				Profile: profile,
				Days:    days,
				Note:    note,
			})
			if err != nil {
				return err
			}
			if flagJSON {
				return termio.PrintRaw(res.Raw)
			}
			if certOut != "" {
				return termio.WriteOut(certOut, []byte(res.Value.Certificate.CertPEM), 0o644)
			}
			return reportIssue(res.Value, outDir, keyFile == "")
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&caRef, "ca", "", "issuing authority")
	fl.StringVar(&csrFile, "csr", "", "the CSR to sign (PEM)")
	fl.StringVar(&keyFile, "key", "", "also store this private key server-side (must match the CSR)")
	fl.StringVar(&profile, "profile", "", "certificate profile")
	fl.IntVar(&days, "days", 0, "validity in days")
	fl.StringVar(&certOut, "cert-out", "", "write just the certificate here")
	fl.StringVar(&outDir, "out", "", "write the certificate and chains into this directory")
	fl.StringVar(&note, "note", "", "free-text note")
	return cmd
}

// reportIssue prints an issuance result and optionally writes the files out.
func reportIssue(res *gocaclient.IssueResult, outDir string, keyNotStored bool) error {
	c := res.Certificate
	termio.OK("issued %s", c.CommonName)
	termio.KV("id", c.ID)
	termio.KV("serial", c.SerialHex)
	termio.KV("authority", c.CAName)
	termio.KV("profile", c.Profile)
	termio.KV("valid until", c.NotAfter.Local().Format("2006-01-02"))
	if len(c.SANs) > 0 {
		termio.KV("SANs", strings.Join(c.SANs, ", "))
	}

	if outDir != "" {
		base := safeFileName(c.CommonName)
		if err := os.MkdirAll(outDir, 0o750); err != nil {
			return err
		}
		if res.PrivateKeyPEM != "" {
			if err := termio.WriteOut(outDir+"/"+base+".key", []byte(res.PrivateKeyPEM), 0o600); err != nil {
				return err
			}
		}
		if err := termio.WriteOut(outDir+"/"+base+".crt", []byte(c.CertPEM), 0o644); err != nil {
			return err
		}
		if res.ChainPEM != "" {
			if err := termio.WriteOut(outDir+"/"+base+"-fullchain.pem",
				[]byte(c.CertPEM+res.ChainPEM), 0o644); err != nil {
				return err
			}
		}
		return nil
	}

	if res.PrivateKeyPEM != "" {
		fmt.Println()
		fmt.Println("Private key:")
		fmt.Print(res.PrivateKeyPEM)
		fmt.Println("Certificate:")
		fmt.Print(c.CertPEM)
		if keyNotStored {
			termio.Warn("this key is not stored on the server; save it now or it is gone")
		}
	}
	return nil
}

// safeFileName makes a file name out of a common name.
func safeFileName(s string) string {
	out := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '.', r == '-', r == '_':
			return r
		default:
			return '_'
		}
	}, s)
	if out == "" {
		return "certificate"
	}
	return out
}

func newCertShowCmd() *cobra.Command {
	var pemOnly bool
	cmd := &cobra.Command{
		Use:   "show <id|serial>",
		Short: "Show one certificate in detail",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			res, err := c.GetCert(ctx, args[0])
			if err != nil {
				return err
			}
			if pemOnly {
				fmt.Print(res.Value.CertPEM)
				return nil
			}
			if flagJSON {
				return termio.PrintRaw(res.Raw)
			}
			cert := res.Value
			termio.Section(cert.CommonName)
			// Field order, labels and time zone all follow internal/cli's
			// printCertSummary so that `goca cert show` and `gocactl cert show`
			// are diff-identical; the end-to-end test compares them directly.
			termio.KV("id", cert.ID)
			termio.KV("common name", cert.CommonName)
			termio.KV("subject", cert.Subject)
			if len(cert.SANs) > 0 {
				termio.KV("SANs", strings.Join(cert.SANs, ", "))
			}
			termio.KV("serial", cert.SerialHex)
			termio.KV("authority", cert.CAName)
			termio.KV("profile", cert.Profile)
			termio.KV("key type", cert.KeyType)
			termio.KV("valid from", cert.NotBefore.Format("2006-01-02 15:04 MST"))
			termio.KV("valid until", fmt.Sprintf("%s (%d days left)", cert.NotAfter.Format("2006-01-02"), cert.DaysLeft()))
			termio.KV("status", cert.EffectiveStatus())
			termio.KV("key stored", cert.HasKey)
			termio.KV("requested by", cert.RequestedBy)
			termio.KV("SHA-256", cert.Fingerprint)
			if info := cert.Info; info != nil {
				termio.KV("signature", info.SignatureAlgorithm)
				termio.KV("key usage", strings.Join(info.KeyUsage, ", "))
				termio.KV("extended key usage", strings.Join(info.ExtKeyUsage, ", "))
			}
			if cert.Note != "" {
				termio.KV("note", cert.Note)
			}
			if cert.Status == "revoked" && cert.RevokedAt != nil {
				termio.KV("revoked", fmt.Sprintf("%s (%s)",
					cert.RevokedAt.Format("2006-01-02 15:04"), pki.ReasonName(cert.RevokeCode)))
			}
			if cert.OnHold() {
				termio.Info("this certificate is on hold; `gocactl cert release %d` lifts it", cert.ID)
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&pemOnly, "pem", false, "print only the certificate PEM")
	return cmd
}

func newCertExportCmd() *cobra.Command {
	var (
		outDir      string
		withKey     bool
		stdout      string
		p12         string
		p12Password string
		fileName    string
	)
	cmd := &cobra.Command{
		Use:   "export <id|serial>",
		Short: "Download a certificate, its chain, key or bundles",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}

			if stdout != "" {
				file, ok := map[string]string{
					"cert": "cert.pem", "chain": "chain.pem",
					"fullchain": "fullchain.pem", "key": "key.pem", "csr": "request.csr",
				}[stdout]
				if !ok {
					return fmt.Errorf("--stdout must be cert, chain, fullchain, key or csr")
				}
				_, data, err := c.DownloadCert(ctx, args[0], file, "")
				if err != nil {
					return err
				}
				_, err = os.Stdout.Write(data)
				return err
			}

			if p12 != "" {
				pw := p12Password
				if pw == "" && termio.Interactive() {
					if pw, err = termio.AskPassword("PKCS#12 export password", true); err != nil {
						return err
					}
				}
				// The password goes in a header, never the query string.
				_, data, err := c.DownloadCert(ctx, args[0], "bundle.p12", pw)
				if err != nil {
					return err
				}
				return termio.WriteOut(p12, data, 0o600)
			}

			if fileName != "" {
				name, data, err := c.DownloadCert(ctx, args[0], fileName, "")
				if err != nil {
					return err
				}
				return writeDownload(outDir, name, data, fileName)
			}

			files := []string{"cert.pem", "chain.pem", "fullchain.pem"}
			if withKey {
				files = append(files, "key.pem")
			}
			for _, file := range files {
				name, data, err := c.DownloadCert(ctx, args[0], file, "")
				if err != nil {
					return err
				}
				if err := writeDownload(outDir, name, data, file); err != nil {
					return err
				}
			}
			return nil
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&outDir, "out", ".", "directory to write into")
	fl.BoolVar(&withKey, "with-key", false, "also download the private key")
	fl.StringVar(&stdout, "stdout", "", "print one artefact: cert|chain|fullchain|key|csr")
	fl.StringVar(&p12, "p12", "", "write a PKCS#12 bundle to this path")
	fl.StringVar(&p12Password, "p12-password", "",
		"password for --p12 (prompted when omitted; prefer the prompt, a flag is visible in ps)")
	fl.StringVar(&fileName, "file", "", "download one named artefact (cert.der, bundle.zip, ...)")
	return cmd
}

func newCertRenewCmd() *cobra.Command {
	var (
		days              int
		sameKey           bool
		caRef, keyType    string
		revokeOld         bool
		outDir, note      string
		expiringIn, doAll int
	)
	cmd := &cobra.Command{
		Use:   "renew <id|serial>",
		Short: "Issue a replacement carrying the same subject and SANs",
		Long: strings.TrimSpace(`
A fresh key is generated by default, since rotating is usually the point -
--same-key keeps a possibly-compromised key in play.`),
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			if expiringIn > 0 {
				res, err := c.RenewExpiring(ctx, expiringIn)
				if err != nil {
					return err
				}
				if flagJSON {
					return termio.PrintRaw(res.Raw)
				}
				termio.OK("renewed %v certificate(s) expiring within %d days", res.Value["renewed"], expiringIn)
				return nil
			}
			if len(args) == 0 {
				return fmt.Errorf("give a certificate id or serial, or use --expiring-in")
			}
			res, err := c.RenewCert(ctx, args[0], gocaclient.RenewInput{
				Days: days, SameKey: sameKey, CARef: caRef,
				KeyType: keyType, RevokeOld: revokeOld, Note: note,
			})
			if err != nil {
				return err
			}
			if flagJSON {
				return termio.PrintRaw(res.Raw)
			}
			return reportIssue(res.Value, outDir, false)
		},
	}
	_ = doAll
	fl := cmd.Flags()
	fl.IntVar(&days, "days", 0, "validity of the replacement")
	fl.BoolVar(&sameKey, "same-key", false, "reuse the stored key instead of generating a new one")
	fl.StringVar(&caRef, "ca", "", "issue the replacement from a different authority")
	fl.StringVar(&keyType, "key-type", "", "algorithm for the new key")
	fl.BoolVar(&revokeOld, "revoke-old", false, "revoke the predecessor as superseded")
	fl.StringVar(&outDir, "out", "", "write the new files into this directory")
	fl.StringVar(&note, "note", "", "free-text note")
	fl.IntVar(&expiringIn, "expiring-in", 0, "renew everything expiring within N days")
	return cmd
}

func newCertHistoryCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "history <id|serial>",
		Short: "Walk a certificate's rotation chain",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			res, err := c.CertHistory(ctx, args[0])
			if err != nil {
				return err
			}
			if flagJSON {
				return termio.PrintRaw(res.Raw)
			}
			chain := res.Value.History
			// The header names the certificate that was asked about, which is
			// the entry the server marked as current.
			subject := args[0]
			for i := range chain {
				if chain[i].ID == res.Value.CurrentID {
					subject = chain[i].CommonName
				}
			}
			termio.Section(fmt.Sprintf("Rotation history for %s", subject))
			t := termio.NewTable("", "id", "serial", "issued", "expires", "status", "key")
			for _, h := range chain {
				marker := " "
				if h.ID == res.Value.CurrentID {
					marker = "→"
				}
				key := "-"
				if h.HasKey {
					key = "stored"
				}
				t.Row(marker, h.ID, h.SerialHex, h.CreatedAt.Format("2006-01-02"),
					h.NotAfter.Format("2006-01-02"), h.EffectiveStatus(), key)
			}
			t.Flush()
			if len(chain) == 1 {
				fmt.Println()
				termio.Info("this certificate has not been renewed")
			}
			return nil
		},
	}
}

func newCertRevokeCmd() *cobra.Command {
	var reason string
	cmd := &cobra.Command{
		Use:   "revoke <id|serial>",
		Short: "Revoke a certificate",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			// Parsed here rather than server-side so that --reason takes the same
			// names as `goca cert revoke` does; pki.ParseReason accepts the numeric
			// codes too, so scripts passing "4" keep working either way.
			code, err := pki.ParseReason(reason)
			if err != nil {
				return err
			}
			c, err := client()
			if err != nil {
				return err
			}
			if err := c.RevokeCert(ctx, args[0], code); err != nil {
				return err
			}
			termio.OK("revoked %s (reason: %s)", args[0], pki.ReasonName(code))
			return nil
		},
	}
	cmd.Flags().StringVar(&reason, "reason", "unspecified", "RFC 5280 revocation reason")
	return cmd
}

func newCertHoldCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "hold <id|serial>",
		Short: "Suspend a certificate reversibly (certificateHold)",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			if err := c.HoldCert(ctx, args[0]); err != nil {
				return err
			}
			termio.OK("%s is on hold; `gocactl cert release %s` lifts it", args[0], args[0])
			return nil
		},
	}
}

func newCertReleaseCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "release <id|serial>",
		Short: "Lift a hold",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			c, err := client()
			if err != nil {
				return err
			}
			if err := c.ReleaseCert(ctx, args[0]); err != nil {
				return err
			}
			termio.OK("released %s", args[0])
			return nil
		},
	}
}

func newCertDeleteCmd() *cobra.Command {
	var yes bool
	cmd := &cobra.Command{
		Use:     "delete <id|serial>",
		Aliases: []string{"rm"},
		Short:   "Delete a certificate record",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx, cancel := cmdContext(cmd)
			defer cancel()
			if !yes {
				if !termio.Interactive() {
					return fmt.Errorf("refusing to delete %q non-interactively; pass --yes", args[0])
				}
				if !termio.AskYesNo(fmt.Sprintf("Delete the record for %q?", args[0]), false) {
					return nil
				}
			}
			c, err := client()
			if err != nil {
				return err
			}
			if err := c.DeleteCert(ctx, args[0]); err != nil {
				return err
			}
			termio.OK("deleted %s", args[0])
			return nil
		},
	}
	cmd.Flags().BoolVar(&yes, "yes", false, "do not ask for confirmation")
	return cmd
}
