// Package service renders and installs OS service units (systemd on Linux,
// launchd on macOS) for the goca web portal, using the running binary's own
// path and the invoking user.
package service

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"
)

// Params describes the unit to render.
type Params struct {
	Name        string   // service name, e.g. "goca-web"
	Description string   //
	BinaryPath  string   // absolute path to the goca binary
	ConfigPath  string   // absolute path to config.yaml
	Args        []string // arguments after the binary, e.g. ["run","web","--port","8080"]
	User        string   // unix user to run as
	Group       string   //
	WorkingDir  string   //
	DataDir     string   // made writable in the sandbox
	Port        int      //
	// UserScope installs into the invoking user's systemd instance rather
	// than the system one.
	UserScope bool
}

// Defaults fills in whatever the caller left empty.
func (p *Params) Defaults() error {
	if p.Name == "" {
		p.Name = "goca-web"
	}
	if p.Description == "" {
		p.Description = "goca certificate authority web portal"
	}
	if p.BinaryPath == "" {
		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("determine binary path: %w", err)
		}
		resolved, err := filepath.EvalSymlinks(exe)
		if err == nil {
			exe = resolved
		}
		p.BinaryPath = exe
	}
	if !filepath.IsAbs(p.BinaryPath) {
		abs, err := filepath.Abs(p.BinaryPath)
		if err != nil {
			return err
		}
		p.BinaryPath = abs
	}
	if p.User == "" {
		u, err := user.Current()
		if err != nil {
			return fmt.Errorf("determine current user: %w", err)
		}
		p.User = u.Username
	}
	if p.Group == "" {
		if g, err := currentGroup(); err == nil {
			p.Group = g
		}
	}
	if p.WorkingDir == "" {
		p.WorkingDir = filepath.Dir(p.BinaryPath)
	}
	return nil
}

func currentGroup() (string, error) {
	u, err := user.Current()
	if err != nil {
		return "", err
	}
	g, err := user.LookupGroupId(u.Gid)
	if err != nil {
		return "", err
	}
	return g.Name, nil
}

// SystemdUnit renders a systemd service unit.
func (p Params) SystemdUnit() string {
	var b strings.Builder
	b.WriteString("# Generated by `goca install web`\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", p.Description)
	b.WriteString("Documentation=https://github.com/mevijays/goca\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")

	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	if !p.UserScope {
		fmt.Fprintf(&b, "User=%s\n", p.User)
		if p.Group != "" {
			fmt.Fprintf(&b, "Group=%s\n", p.Group)
		}
	}
	fmt.Fprintf(&b, "WorkingDirectory=%s\n", p.WorkingDir)
	if p.ConfigPath != "" {
		fmt.Fprintf(&b, "Environment=GOCA_CONFIG=%s\n", p.ConfigPath)
	}
	fmt.Fprintf(&b, "ExecStart=%s %s\n", p.BinaryPath, strings.Join(p.Args, " "))
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=5s\n")
	b.WriteString("TimeoutStopSec=20s\n")
	b.WriteString("KillSignal=SIGTERM\n\n")

	b.WriteString("# Hardening\n")
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("PrivateTmp=true\n")
	b.WriteString("ProtectSystem=full\n")
	b.WriteString("ProtectKernelTunables=true\n")
	b.WriteString("ProtectKernelModules=true\n")
	b.WriteString("ProtectControlGroups=true\n")
	b.WriteString("RestrictSUIDSGID=true\n")
	b.WriteString("LockPersonality=true\n")
	if p.DataDir != "" {
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", p.DataDir)
	}
	if p.ConfigPath != "" {
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", filepath.Dir(p.ConfigPath))
	}
	// Ports below 1024 need the capability; granting it is cheaper than root.
	if p.Port > 0 && p.Port < 1024 {
		b.WriteString("AmbientCapabilities=CAP_NET_BIND_SERVICE\n")
		b.WriteString("CapabilityBoundingSet=CAP_NET_BIND_SERVICE\n")
	}
	b.WriteString("\n[Install]\n")
	if p.UserScope {
		b.WriteString("WantedBy=default.target\n")
	} else {
		b.WriteString("WantedBy=multi-user.target\n")
	}
	return b.String()
}

// LaunchdPlist renders a macOS launchd job.
func (p Params) LaunchdPlist() string {
	label := "com.goca." + strings.TrimPrefix(p.Name, "goca-")
	var args strings.Builder
	fmt.Fprintf(&args, "    <string>%s</string>\n", p.BinaryPath)
	for _, a := range p.Args {
		fmt.Fprintf(&args, "    <string>%s</string>\n", a)
	}
	logDir := p.DataDir
	if logDir == "" {
		logDir = "/tmp"
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by `+"`goca install web`"+` -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>%s</string>
  <key>ProgramArguments</key>
  <array>
%s  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>GOCA_CONFIG</key>
    <string>%s</string>
  </dict>
  <key>WorkingDirectory</key>
  <string>%s</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>%s/goca-web.log</string>
  <key>StandardErrorPath</key>
  <string>%s/goca-web.err.log</string>
</dict>
</plist>
`, label, args.String(), p.ConfigPath, p.WorkingDir, logDir, logDir)
}

// UnitPath returns where the unit file belongs on this platform.
func (p Params) UnitPath() (string, error) {
	switch runtime.GOOS {
	case "linux":
		if p.UserScope {
			home, err := os.UserHomeDir()
			if err != nil {
				return "", err
			}
			return filepath.Join(home, ".config/systemd/user", p.Name+".service"), nil
		}
		return filepath.Join("/etc/systemd/system", p.Name+".service"), nil
	case "darwin":
		label := "com.goca." + strings.TrimPrefix(p.Name, "goca-")
		if p.UserScope {
			home, err := os.UserHomeDir()
			if err != nil {
				return "", err
			}
			return filepath.Join(home, "Library/LaunchAgents", label+".plist"), nil
		}
		return filepath.Join("/Library/LaunchDaemons", label+".plist"), nil
	default:
		return "", fmt.Errorf("service installation is not supported on %s; "+
			"run `goca run web` under your own supervisor", runtime.GOOS)
	}
}

// Render produces the unit file contents for this platform.
func (p Params) Render() (string, error) {
	switch runtime.GOOS {
	case "linux":
		return p.SystemdUnit(), nil
	case "darwin":
		return p.LaunchdPlist(), nil
	default:
		return "", fmt.Errorf("no service template for %s", runtime.GOOS)
	}
}

// Install writes the unit file, creating parent directories.
func (p Params) Install() (string, error) {
	path, err := p.UnitPath()
	if err != nil {
		return "", err
	}
	content, err := p.Render()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("create %s: %w (try again with sudo)", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w (try again with sudo)", path, err)
	}
	return path, nil
}

// Uninstall removes the unit file after stopping the service.
func (p Params) Uninstall() (string, error) {
	path, err := p.UnitPath()
	if err != nil {
		return "", err
	}
	switch runtime.GOOS {
	case "linux":
		_ = run(p.systemctl("stop", p.Name)...)
		_ = run(p.systemctl("disable", p.Name)...)
	case "darwin":
		_ = run("launchctl", "unload", path)
	}
	if err := os.Remove(path); err != nil {
		return "", err
	}
	if runtime.GOOS == "linux" {
		_ = run(p.systemctl("daemon-reload")...)
	}
	return path, nil
}

// Enable reloads the manager and starts the service now.
func (p Params) Enable() error {
	path, err := p.UnitPath()
	if err != nil {
		return err
	}
	switch runtime.GOOS {
	case "linux":
		if err := run(p.systemctl("daemon-reload")...); err != nil {
			return err
		}
		return run(p.systemctl("enable", "--now", p.Name)...)
	case "darwin":
		_ = run("launchctl", "unload", path)
		return run("launchctl", "load", "-w", path)
	}
	return fmt.Errorf("cannot enable services on %s", runtime.GOOS)
}

// Commands returns the manual follow-up commands for the operator.
func (p Params) Commands() []string {
	path, _ := p.UnitPath()
	switch runtime.GOOS {
	case "linux":
		sc := "sudo systemctl"
		if p.UserScope {
			sc = "systemctl --user"
		}
		return []string{
			sc + " daemon-reload",
			sc + " enable --now " + p.Name,
			sc + " status " + p.Name,
			strings.Replace(sc, "systemctl", "journalctl", 1) + " -u " + p.Name + " -f",
		}
	case "darwin":
		return []string{
			"launchctl load -w " + path,
			"launchctl list | grep goca",
			"launchctl unload " + path,
		}
	}
	return nil
}

func (p Params) systemctl(args ...string) []string {
	cmd := []string{"systemctl"}
	if p.UserScope {
		cmd = append(cmd, "--user")
	}
	return append(cmd, args...)
}

func run(args ...string) error {
	if len(args) == 0 {
		return nil
	}
	cmd := exec.Command(args[0], args[1:]...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// Detect reports whether a service manager is available on this host.
func Detect() (manager string, available bool) {
	switch runtime.GOOS {
	case "linux":
		if _, err := exec.LookPath("systemctl"); err == nil {
			return "systemd", true
		}
		return "systemd", false
	case "darwin":
		if _, err := exec.LookPath("launchctl"); err == nil {
			return "launchd", true
		}
		return "launchd", false
	}
	return runtime.GOOS, false
}
